version: '3'
services:
  rabbitmq:
    image: zobiz/xray-rabbitmq
    container_name: xray-rabbitmq
    hostname: vault.thecodemountains.com
    entrypoint: ""
    command: ./setRabbitCluster.sh
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672
      - 4369:4369
      - 127.0.0.1:25672:25672
    volumes:
      - /mnt/samsung/code/artifactory/jfrog-docker-compose/third-party/rabbitmq/setRabbitCluster.sh:/setRabbitCluster.sh
      - /mnt/samsung/code/artifactory/jfrog-docker-compose/third-party/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /mnt/samsung/code/artifactory/jfrog-docker-compose/root/.jfrog/.jfrog/xray/var/data/rabbitmq:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    restart: always
    extra_hosts:
      - "${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}:${JF_SHARED_RABBITMQ_ACTIVE_NODE_IP}"
    environment:
      - JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME=${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}
      - JF_SHARED_RABBITMQ_CLEAN=N # should be in sync with shared.rabbitMq.clean
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
